[__config__]
oldver = "oldver.json"
newver = "newver.json"

# arch repackages

[clang-gccless]
source = "archpkg"
archpkg = "clang"
strip_release = true

[obsidian-custom]
source = "archpkg"
archpkg = "obsidian"
strip_release = true

[signal-desktop-custom]
source = "archpkg"
archpkg = "signal-desktop"
strip_release = true

# personal projects

[niri-custom]
source = "git"
git = "https://github.com/spaceavenue/niri.git"
branch = "custom"
use_commit = true

[rusty-wl-utils]
source = "git"
git = "https://github.com/spaceavenue/rusty-wl-utils.git"
use_commit = true

[rustclip]
source = "git"
git = "https://github.com/spaceavenue/rustclip.git"
use_commit = true

[qoz]
source = "git"
git = "https://github.com/spaceavenue/qoz.git"
use_commit = true

[udiskrs]
source = "git"
git = "https://github.com/spaceavenue/udiskrs.git"
use_commit = true

# github projects (forked/patched when building)

[wtype-custom]
source = "github"
github = "atx/wtype"
prefix = "v"

[imv-custom]
source = "git"
git = "https://git.sr.ht/~exec64/imv"
prefix = "v"

[swaylock-time]
source = "github"
github = "swaywm/swaylock"
use_max_tag = true
prefix = "v"

[ttc-iosevka-collection]
source = "github"
github = "be5invis/Iosevka"
use_max_tag = true
prefix = "v"

[uutils-coreutils]
source = "github"
github = "uutils/coreutils"
use_max_tag = true

[vesktop-custom]
source = "github"
github = "Vencord/Vesktop"
use_latest_release = true
prefix = "v"

[yt-dlp-ejs-npm-bin]
source = "github"
github = "yt-dlp/ejs"
use_max_release = true
